[package]
name = "aoc-13"
version = "0.1.0"
authors = ["Ben Sandwick <ben.sandwick@foxbytegames.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
